// This file contains the Printer HW setup including Extruders, Fans, Bed, Sensors etc.

#include "Configuration.h"

unsigned char fillamentConfig[EXTRUDER_TYPE_COUNT][FILLAMENT_COUNT][5] = { 0 };

void fillament_config_init();

void configuration_init()
{
    // init all fillament configurations
    fillament_config_init();
}

void fillament_config_init()
{
    // NOTE: if needed a hotend temp above 255, we actually use the first 2 bytes for it, so cast to int.
    //----- EXTRUDER_TYPE_BUDASCHNOZZLE -----//
    // FILLAMENT_ABS:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_ABS][ID_HOTEND_TEMP]) = 230;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_ABS][ID_HPB_TEMP] = 85;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_ABS][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_ABS][ID_INFO] = INFO_NOZZLE_0_35;

    // FILLAMENT_PLA:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_PLA][ID_HOTEND_TEMP]) = 180;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_PLA][ID_HPB_TEMP] = 50;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_PLA][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_PLA][ID_INFO] = INFO_NOZZLE_0_35;

    // FILLAMENT_HIPS:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_HIPS][ID_HOTEND_TEMP]) = 230;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_HIPS][ID_HPB_TEMP] = 85;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_HIPS][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_HIPS][ID_INFO] = INFO_NOZZLE_0_35;

    // FILLAMENT_FLEXIBLE:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_FLEXIBLE][ID_HOTEND_TEMP]) = 230;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_FLEXIBLE][ID_HPB_TEMP] = 0;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_FLEXIBLE][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_FLEXIBLE][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_50;

    // FILLAMENT_LAYBRICK:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_LAYBRICK][ID_HOTEND_TEMP]) = 185;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_LAYBRICK][ID_HPB_TEMP] = 50;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_LAYBRICK][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_LAYBRICK][ID_INFO] = INFO_NOZZLE_0_35;

    // FILLAMENT_LAYWOO_D3:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_LAYWOO_D3][ID_HOTEND_TEMP]) = 180;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_LAYWOO_D3][ID_HPB_TEMP] = 50;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_LAYWOO_D3][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_LAYWOO_D3][ID_INFO] = INFO_NOZZLE_0_50;

    // FILLAMENT_NYLON_618:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_NYLON_618][ID_HOTEND_TEMP]) = 235;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_NYLON_618][ID_HPB_TEMP] = 85;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_NYLON_618][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_NYLON_618][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILLAMENT_NYLON_645:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_NYLON_645][ID_HOTEND_TEMP]) = 235;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_NYLON_645][ID_HPB_TEMP] = 85;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_NYLON_645][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_NYLON_645][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILLAMENT_NYLON_BRIDGE:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_NYLON_BRIDGE][ID_HOTEND_TEMP]) = 235;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_NYLON_BRIDGE][ID_HPB_TEMP] = 85;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_NYLON_BRIDGE][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_NYLON_BRIDGE][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILLAMENT_PVA:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_PVA][ID_HOTEND_TEMP]) = 190;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_PVA][ID_HPB_TEMP] = 85;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_PVA][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_PVA][ID_INFO] = INFO_NOZZLE_0_35;

    // FILLAMENT_T_GLASE:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_T_GLASE][ID_HOTEND_TEMP]) = 230;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_T_GLASE][ID_HPB_TEMP] = 50;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_T_GLASE][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILLAMENT_T_GLASE][ID_INFO] = INFO_NOZZLE_0_35;


    //----- EXTRUDER_TYPE_HEXAGON -----//
    // FILLAMENT_ABS:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_ABS][ID_HOTEND_TEMP]) = 240;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_ABS][ID_HPB_TEMP] = 110;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_ABS][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_ABS][ID_INFO] = INFO_NOZZLE_0_35;

    // FILLAMENT_PLA:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_PLA][ID_HOTEND_TEMP]) = 205;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_PLA][ID_HPB_TEMP] = 60;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_PLA][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_PLA][ID_INFO] = INFO_NOZZLE_0_35;

    // FILLAMENT_HIPS:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_HIPS][ID_HOTEND_TEMP]) = 240;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_HIPS][ID_HPB_TEMP] = 110;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_HIPS][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_HIPS][ID_INFO] = INFO_NOZZLE_0_35;

    // FILLAMENT_FLEXIBLE:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_FLEXIBLE][ID_HOTEND_TEMP]) = 230;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_FLEXIBLE][ID_HPB_TEMP] = 0;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_FLEXIBLE][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_FLEXIBLE][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_50;

    // FILLAMENT_LAYBRICK:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_LAYBRICK][ID_HOTEND_TEMP]) = 190;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_LAYBRICK][ID_HPB_TEMP] = 60;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_LAYBRICK][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_LAYBRICK][ID_INFO] = INFO_NOZZLE_0_35;

    // FILLAMENT_LAYWOO_D3:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_LAYWOO_D3][ID_HOTEND_TEMP]) = 190;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_LAYWOO_D3][ID_HPB_TEMP] = 60;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_LAYWOO_D3][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_LAYWOO_D3][ID_INFO] = INFO_NOZZLE_0_50;

    // FILLAMENT_NYLON_618:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_NYLON_618][ID_HOTEND_TEMP]) = 240;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_NYLON_618][ID_HPB_TEMP] = 110;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_NYLON_618][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_NYLON_618][ID_INFO] = INFO_NOZZLE_0_35;

    // FILLAMENT_NYLON_645:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_NYLON_645][ID_HOTEND_TEMP]) = 240;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_NYLON_645][ID_HPB_TEMP] = 110;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_NYLON_645][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_NYLON_645][ID_INFO] = INFO_NOZZLE_0_35;

    // FILLAMENT_NYLON_BRIDGE:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_NYLON_BRIDGE][ID_HOTEND_TEMP]) = 245;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_NYLON_BRIDGE][ID_HPB_TEMP] = 110;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_NYLON_BRIDGE][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_NYLON_BRIDGE][ID_INFO] = INFO_NOZZLE_0_35;

    // FILLAMENT_PVA:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_PVA][ID_HOTEND_TEMP]) = 190;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_PVA][ID_HPB_TEMP] = 85;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_PVA][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_PVA][ID_INFO] = INFO_NOZZLE_0_35;

    // FILLAMENT_T_GLASE:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_T_GLASE][ID_HOTEND_TEMP]) = 245;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_T_GLASE][ID_HPB_TEMP] = 60;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_T_GLASE][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_HEXAGON][FILLAMENT_T_GLASE][ID_INFO] = INFO_NOZZLE_0_35;


    //----- EXTRUDER_TYPE_FLEXYSTRUDER -----//
    // FILLAMENT_ABS:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_ABS][ID_HOTEND_TEMP]) = 230;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_ABS][ID_HPB_TEMP] = 85;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_ABS][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_ABS][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILLAMENT_PLA:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_PLA][ID_HOTEND_TEMP]) = 180;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_PLA][ID_HPB_TEMP] = 50;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_PLA][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_PLA][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILLAMENT_HIPS:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_HIPS][ID_HOTEND_TEMP]) = 230;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_HIPS][ID_HPB_TEMP] = 85;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_HIPS][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_HIPS][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILLAMENT_FLEXIBLE:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_FLEXIBLE][ID_HOTEND_TEMP]) = 230;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_FLEXIBLE][ID_HPB_TEMP] = 0;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_FLEXIBLE][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_FLEXIBLE][ID_INFO] = INFO_NOZZLE_0_50;

    // FILLAMENT_LAYBRICK:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_LAYBRICK][ID_HOTEND_TEMP]) = 185;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_LAYBRICK][ID_HPB_TEMP] = 50;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_LAYBRICK][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_LAYBRICK][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILLAMENT_LAYWOO_D3:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_LAYWOO_D3][ID_HOTEND_TEMP]) = 180;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_LAYWOO_D3][ID_HPB_TEMP] = 50;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_LAYWOO_D3][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_LAYWOO_D3][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_50;

    // FILLAMENT_NYLON_618:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_NYLON_618][ID_HOTEND_TEMP]) = 235;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_NYLON_618][ID_HPB_TEMP] = 85;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_NYLON_618][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_NYLON_618][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILLAMENT_NYLON_645:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_NYLON_645][ID_HOTEND_TEMP]) = 235;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_NYLON_645][ID_HPB_TEMP] = 85;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_NYLON_645][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_NYLON_645][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILLAMENT_NYLON_BRIDGE:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_NYLON_BRIDGE][ID_HOTEND_TEMP]) = 235;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_NYLON_BRIDGE][ID_HPB_TEMP] = 85;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_NYLON_BRIDGE][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_NYLON_BRIDGE][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILLAMENT_PVA:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_PVA][ID_HOTEND_TEMP]) = 190;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_PVA][ID_HPB_TEMP] = 85;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_PVA][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_PVA][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILLAMENT_T_GLASE:
    *((int16_t*)&fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_T_GLASE][ID_HOTEND_TEMP]) = 230;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_T_GLASE][ID_HPB_TEMP] = 50;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_T_GLASE][ID_FAN_SPEED] = 0;
    fillamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILLAMENT_T_GLASE][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;
}