// This file contains the Printer HW setup including Extruders, Fans, Bed, Sensors etc.

#include "Configuration.h"

unsigned char filamentConfig[EXTRUDER_TYPE_COUNT][FILAMENT_COUNT][5] = { 0 };

void filament_config_init();

void configuration_init()
{
    // init all filament configurations
    filament_config_init();
}

void filament_config_init()
{
    // NOTE: if needed a hotend temp above 255, we actually use the first 2 bytes for it, so cast to int.
    //----- EXTRUDER_TYPE_BUDASCHNOZZLE -----//
    // FILAMENT_ABS:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_ABS][ID_HOTEND_TEMP]) = 230;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_ABS][ID_HPB_TEMP] = 85;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_ABS][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_ABS][ID_INFO] = INFO_NOZZLE_0_35;

    // FILAMENT_PLA:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_PLA][ID_HOTEND_TEMP]) = 180;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_PLA][ID_HPB_TEMP] = 50;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_PLA][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_PLA][ID_INFO] = INFO_NOZZLE_0_35;

    // FILAMENT_HIPS:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_HIPS][ID_HOTEND_TEMP]) = 230;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_HIPS][ID_HPB_TEMP] = 85;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_HIPS][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_HIPS][ID_INFO] = INFO_NOZZLE_0_35;

    // FILAMENT_FLEXIBLE:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_FLEXIBLE][ID_HOTEND_TEMP]) = 230;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_FLEXIBLE][ID_HPB_TEMP] = 0;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_FLEXIBLE][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_FLEXIBLE][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_50;

    // FILAMENT_LAYBRICK:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_LAYBRICK][ID_HOTEND_TEMP]) = 185;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_LAYBRICK][ID_HPB_TEMP] = 50;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_LAYBRICK][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_LAYBRICK][ID_INFO] = INFO_NOZZLE_0_35;

    // FILAMENT_LAYWOO_D3:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_LAYWOO_D3][ID_HOTEND_TEMP]) = 180;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_LAYWOO_D3][ID_HPB_TEMP] = 50;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_LAYWOO_D3][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_LAYWOO_D3][ID_INFO] = INFO_NOZZLE_0_50;

    // FILAMENT_NYLON_618:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_NYLON_618][ID_HOTEND_TEMP]) = 235;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_NYLON_618][ID_HPB_TEMP] = 85;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_NYLON_618][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_NYLON_618][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILAMENT_NYLON_645:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_NYLON_645][ID_HOTEND_TEMP]) = 235;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_NYLON_645][ID_HPB_TEMP] = 85;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_NYLON_645][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_NYLON_645][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILAMENT_NYLON_BRIDGE:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_NYLON_BRIDGE][ID_HOTEND_TEMP]) = 235;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_NYLON_BRIDGE][ID_HPB_TEMP] = 85;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_NYLON_BRIDGE][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_NYLON_BRIDGE][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILAMENT_PVA:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_PVA][ID_HOTEND_TEMP]) = 190;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_PVA][ID_HPB_TEMP] = 85;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_PVA][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_PVA][ID_INFO] = INFO_NOZZLE_0_35;

    // FILAMENT_T_GLASE:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_T_GLASE][ID_HOTEND_TEMP]) = 230;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_T_GLASE][ID_HPB_TEMP] = 50;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_T_GLASE][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_BUDASCHNOZZLE][FILAMENT_T_GLASE][ID_INFO] = INFO_NOZZLE_0_35;


    //----- EXTRUDER_TYPE_HEXAGON -----//
    // FILAMENT_ABS:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_ABS][ID_HOTEND_TEMP]) = 240;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_ABS][ID_HPB_TEMP] = 110;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_ABS][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_ABS][ID_INFO] = INFO_NOZZLE_0_35;

    // FILAMENT_PLA:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_PLA][ID_HOTEND_TEMP]) = 205;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_PLA][ID_HPB_TEMP] = 60;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_PLA][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_PLA][ID_INFO] = INFO_NOZZLE_0_35;

    // FILAMENT_HIPS:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_HIPS][ID_HOTEND_TEMP]) = 240;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_HIPS][ID_HPB_TEMP] = 110;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_HIPS][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_HIPS][ID_INFO] = INFO_NOZZLE_0_35;

    // FILAMENT_FLEXIBLE:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_FLEXIBLE][ID_HOTEND_TEMP]) = 230;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_FLEXIBLE][ID_HPB_TEMP] = 0;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_FLEXIBLE][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_FLEXIBLE][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_50;

    // FILAMENT_LAYBRICK:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_LAYBRICK][ID_HOTEND_TEMP]) = 190;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_LAYBRICK][ID_HPB_TEMP] = 60;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_LAYBRICK][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_LAYBRICK][ID_INFO] = INFO_NOZZLE_0_35;

    // FILAMENT_LAYWOO_D3:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_LAYWOO_D3][ID_HOTEND_TEMP]) = 190;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_LAYWOO_D3][ID_HPB_TEMP] = 60;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_LAYWOO_D3][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_LAYWOO_D3][ID_INFO] = INFO_NOZZLE_0_50;

    // FILAMENT_NYLON_618:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_NYLON_618][ID_HOTEND_TEMP]) = 240;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_NYLON_618][ID_HPB_TEMP] = 110;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_NYLON_618][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_NYLON_618][ID_INFO] = INFO_NOZZLE_0_35;

    // FILAMENT_NYLON_645:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_NYLON_645][ID_HOTEND_TEMP]) = 240;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_NYLON_645][ID_HPB_TEMP] = 110;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_NYLON_645][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_NYLON_645][ID_INFO] = INFO_NOZZLE_0_35;

    // FILAMENT_NYLON_BRIDGE:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_NYLON_BRIDGE][ID_HOTEND_TEMP]) = 245;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_NYLON_BRIDGE][ID_HPB_TEMP] = 110;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_NYLON_BRIDGE][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_NYLON_BRIDGE][ID_INFO] = INFO_NOZZLE_0_35;

    // FILAMENT_PVA:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_PVA][ID_HOTEND_TEMP]) = 190;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_PVA][ID_HPB_TEMP] = 85;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_PVA][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_PVA][ID_INFO] = INFO_NOZZLE_0_35;

    // FILAMENT_T_GLASE:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_T_GLASE][ID_HOTEND_TEMP]) = 245;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_T_GLASE][ID_HPB_TEMP] = 60;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_T_GLASE][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_HEXAGON][FILAMENT_T_GLASE][ID_INFO] = INFO_NOZZLE_0_35;


    //----- EXTRUDER_TYPE_FLEXYSTRUDER -----//
    // FILAMENT_ABS:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_ABS][ID_HOTEND_TEMP]) = 230;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_ABS][ID_HPB_TEMP] = 85;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_ABS][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_ABS][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILAMENT_PLA:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_PLA][ID_HOTEND_TEMP]) = 180;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_PLA][ID_HPB_TEMP] = 50;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_PLA][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_PLA][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILAMENT_HIPS:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_HIPS][ID_HOTEND_TEMP]) = 230;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_HIPS][ID_HPB_TEMP] = 85;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_HIPS][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_HIPS][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILAMENT_FLEXIBLE:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_FLEXIBLE][ID_HOTEND_TEMP]) = 230;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_FLEXIBLE][ID_HPB_TEMP] = 0;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_FLEXIBLE][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_FLEXIBLE][ID_INFO] = INFO_NOZZLE_0_50;

    // FILAMENT_LAYBRICK:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_LAYBRICK][ID_HOTEND_TEMP]) = 185;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_LAYBRICK][ID_HPB_TEMP] = 50;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_LAYBRICK][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_LAYBRICK][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILAMENT_LAYWOO_D3:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_LAYWOO_D3][ID_HOTEND_TEMP]) = 180;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_LAYWOO_D3][ID_HPB_TEMP] = 50;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_LAYWOO_D3][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_LAYWOO_D3][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_50;

    // FILAMENT_NYLON_618:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_NYLON_618][ID_HOTEND_TEMP]) = 235;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_NYLON_618][ID_HPB_TEMP] = 85;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_NYLON_618][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_NYLON_618][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILAMENT_NYLON_645:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_NYLON_645][ID_HOTEND_TEMP]) = 235;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_NYLON_645][ID_HPB_TEMP] = 85;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_NYLON_645][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_NYLON_645][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILAMENT_NYLON_BRIDGE:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_NYLON_BRIDGE][ID_HOTEND_TEMP]) = 235;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_NYLON_BRIDGE][ID_HPB_TEMP] = 85;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_NYLON_BRIDGE][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_NYLON_BRIDGE][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILAMENT_PVA:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_PVA][ID_HOTEND_TEMP]) = 190;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_PVA][ID_HPB_TEMP] = 85;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_PVA][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_PVA][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;

    // FILAMENT_T_GLASE:
    *((int16_t*)&filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_T_GLASE][ID_HOTEND_TEMP]) = 230;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_T_GLASE][ID_HPB_TEMP] = 50;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_T_GLASE][ID_FAN_SPEED] = 0;
    filamentConfig[EXTRUDER_TYPE_FLEXYSTRUDER][FILAMENT_T_GLASE][ID_INFO] = INFO_NOT_RECOMMENDED + INFO_NOZZLE_0_35;
}